package com.powerfin.helper;

public class BatchProcessHelper {

	public final static String TERM_INTEREST_TRANSACTION_MODULE = "BATCHTERMINTEREST";
	
	
	public final static String LOAN_INTEREST_TRANSACTION_MODULE = "BATCHLOANINTEREST";
	public final static String RECEIVABLE_SALE_PORTFOLIO_TRANSACTION_MODULE = "BATCHRECEIVABLESALEPORTFOLIO";
	public final static String PAYABLE_SALE_PORTFOLIO_TRANSACTION_MODULE = "BATCHPAYABLESALEPORTFOLIO";
	public final static String UTILITY_SALE_PORTFOLIO_TRANSACTION_MODULE = "BATCHUTILITYSALEPORTFOLIO";
	public final static String SPREAD_PURCHASE_PORTFOLIO_TRANSACTION_MODULE = "BATCHSPREADPURCHASEPORTFOLIO";
}
